# Generated by Django 3.0.7 on 2020-08-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 0), ('Part Time', 1)], max_length=100),
        ),
    ]
