# Generated by Django 3.0.7 on 2020-08-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200815_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[(0, 'Full Time'), (1, 'Part Time')], max_length=100),
        ),
    ]
