# Generated by Django 3.0.7 on 2020-08-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cv',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
