# Generated by Django 3.0.7 on 2020-09-07 13:33

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20200907_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to=job.models.upload_image),
            preserve_default=False,
        ),
    ]
