# Generated by Django 3.0.7 on 2020-09-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_auto_20200907_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
